// SAMPLEDATATHEORY.js
export const questionPaperData = {
  "assessment_id": 100169,
  "assessment_name": "SSC Class X Mathematics Examination",
  "assessment_type": "STANDARD",
  "user_ass_id": 101017,
  "user_ass_div_id": null,
  "ass_div_name": null,
  "sub_division_data": [],
  "exam_details": {
    "board": "MAHARASHTRA STATE BOARD OF SECONDARY AND \\ HIGHER SECONDARY EDUCATION, PUNE",
    "examination": "SSC EXAMINATION",
    "class": "X",
    "subject": "MATHEMATICS",
    "time_allowed": "3 Hours",
    "max_marks": "80"
  },
  "instructions": [
    "All questions are compulsory.",
    "Use of calculator is not allowed.",
    "The numbers to the right indicate full marks."
  ],
  "sections": [
    {
      "name": "SECTION A",
      "questions": [
        {
          "question_id": 104393,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "Solve the quadratic equation: $x^2 - 7x + 12 = 0$ using factorization method.",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "Solve the quadratic equation: "
            },
            {
              "type": "latex",
              "text": "$x^2 - 7x + 12 = 0$"
            },
            {
              "type": "text",
              "text": " using factorization method."
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
           "instruction": "Attempt any One of the following sub questions:" // Added instruction
        }
      ]
    },
    {
      "name": "SECTION B",
      "questions": [
        {
          "question_id": 104394,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "Find the coordinates of the midpoint of the line segment joining the points A(2, 3) and B(6, 7).",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "Find the coordinates of the midpoint of the line segment joining the points A(2, 3) and B(6, 7)."
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
          "instruction": "Attempt any One of the following sub questions:" // Added instruction
        },
        {
          "question_id": 104395,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "In triangle ABC, D is a point on side BC such that AD $\\perp$ BC. If BD = 4 cm, DC = 9 cm and AD = 6 cm, find: (i) AB",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "In triangle ABC, D is a point on side BC such that AD "
            },
            {
              "type": "latex",
              "text": "$\\perp$"
            },
            {
              "type": "text",
              "text": " BC. If BD = 4 cm, DC = 9 cm and AD = 6 cm, find: (i) AB (ii) AC (iii) Area of triangle ABC"
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false
        },
        {
          "question_id": 104398,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "A bag contains 5 red balls and 3 blue balls. If one ball is drawn at random, find the probability of getting a red ball.",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "A bag contains 5 red balls and 3 blue balls. If one ball is drawn at random, find the probability of getting a red ball."
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
          "instruction": "Attempt any One of the following sub questions:" // Added instruction
        }
      ]
    },
    {
      "name": "SECTION C",
      "questions": [
        {
          "question_id": 104399,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "Solve the quadratic equation: $x^2 - 7x + 12 = 0$ using factorization method.",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "Solve the quadratic equation: "
            },
            {
              "type": "latex",
              "text": "$x^2 - 7x + 12 = 0$"
            },
            {
              "type": "text",
              "text": " using factorization method."
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
          "instruction": "Attempt any One of the following sub questions:" // Added instruction
        },
        {
          "question_id": 104400,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "Find the coordinates of the midpoint of the line segment joining the points A(2, 3) and B(6, 7).",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "Find the coordinates of the midpoint of the line segment joining the points A(2, 3) and B(6, 7)."
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false
        },
      ]
    },
    {
      "name": "SECTION D",
      "questions": [
        
       {
          "question_id": 104395,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "In triangle ABC, D is a point on side BC such that AD $\\perp$ BC. If BD = 4 cm, DC = 9 cm and AD = 6 cm, find: (i) AB",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "In triangle ABC, D is a point on side BC such that AD "
            },
            {
              "type": "latex",
              "text": "$\\perp$"
            },
            {
              "type": "text",
              "text": " BC. If BD = 4 cm, DC = 9 cm and AD = 6 cm, find: (i) AB (ii) AC (iii) Area of triangle ABC"
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
          "instruction": "Attempt any One of the following sub questions:" // Added instruction
        },
         {
          "question_id": 104404,
          "topic_id": null,
          "chapter_id": null,
          "subject_id": null,
          "course_id": null,
          "question_type_id": null,
          "question_type": "Theory",
          "question_latex": "The following table shows the marks obtained by 40 students in a Mathematics test:",
          "question_diagrams_url": [],
          "description_diagrams_url": [],
          "answer_latex": null,
          "answer_description": null,
          "marks": 8,
          "complexity": "average",
          "option1_latex": null,
          "option2_latex": null,
          "option3_latex": null,
          "option4_latex": null,
          "option5_latex": null,
          "option1_img": null,
          "option2_img": null,
          "option3_img": null,
          "option4_img": null,
          "option5_img": null,
          "ques_line_by_latex": [
            {
              "type": "text",
              "text": "The following table shows the marks obtained by 40 students in a Mathematics test:"
            }
          ],
          "desc_line_by_latex": null,
          "negative_marks": null,
          "passage_latex": null,
          "passage_diagram": null,
          "passage_line_by_latex": null,
          "passage_image_url": null,
          "raw_data": null,
          "created_by": null,
          "creation_date": "2024-07-30T00:00:00.000000",
          "last_updation_date": null,
          "last_update_by": null,
          "status": "Active",
          "attribute1": null,
          "attribute2": null,
          "attribute3": null,
          "attribute4": null,
          "attribute5": null,
          "attribute6": null,
          "attribute7": null,
          "attribute8": null,
          "attribute9": null,
          "attribute10": null,
          "user_answer": null,
          "correct_option": null,
          "attempt_status": null,
          "book_mark_status": false,
          "table": {
            "headers": [
              "\\textbf{Marks}",
              "\\textbf{0-10}",
              "\\textbf{10-20}",
              "\\textbf{20-30}",
              "\\textbf{30-40}",
              "\\textbf{40-50}"
            ],
            "rows": [
              {
                "row_name": "\\textbf{Frequency}",
                "values": [
                  "4",
                  "8",
                  "12",
                  "10",
                  "6"
                ]
              }
            ]
          }
        }
      ]
    }
  ],
  "footer": {
    "code": "10TH29072025",
    "page_numbers": [1, 2],
    "end_marker": "\\textbf{** END **}"
  }
};
